
FALLBACK_RECOMMENDATIONS = {
    # Score 0-2 (Very Low)
    1: [
        "The current combination seems a bit disjointed; consider starting with a neutral base and adding one color.",
        "Fit is key! Ensure your clothes are tailored to your body shape for a sharper look.",
        "The colors here might be clashing. Try using a color wheel to find complementary shades.",
        "This outfit feels a bit chaotic. Simplifying the patterns could make a huge difference.",
        "Consider the occasion. This look might be too casual or too formal for the intended event.",
        "Accessories seem to be missing or mismatched. A simple watch or necklace could help.",
        "The silhouette isn't quite working. Try balancing a loose top with tighter bottoms or vice versa.",
        "Proportions seem off. High-waisted pants or a tucked-in shirt might improve the lines.",
        "The fabric choices don't seem to mesh well. Mixing textures requires careful balance.",
        "It looks like you threw this together quickly. A bit more intentionality in matching would help.",
        "The shoes don't quite match the vibe of the rest of the outfit. Try a more classic style.",
        "Layering is clunky here. Ensure under-layers are thinner than outer-layers.",
        "The grooming or presentation might be distracting from the outfit itself.",
        "This style assumes a certain confidence; make sure you feel good in what you're wearing.",
        "Don't be afraid to experiment, but maybe start with classic combinations first.",
        "The outfit lacks a focal point. Everything is fighting for attention.",
        "The color palette is a bit dull. A pop of color could bring this to life.",
        "Conversely, too many bright colors can be overwhelming. Try grounding with navy or black.",
        "The hemline seems incorrect for your height. modifications might be needed.",
        "Ironing or steaming your clothes would instantly upgrade this look.",
        "The style feels a bit dated. Updating one piece to a modern cut could help.",
        "It's hard to tell your personal style from this. meaningful pieces needed.",
        "The fit around the shoulders or waist seems loose/tight. Comfort is style!",
        "Try following the 'rule of thirds' in your outfit proportions.",
        "This looks a bit 'costumey'. Aim for something more natural and effortless.",
        "The bag or carry-on item conflicts with the outfit's aesthetic.",
        "Socks can make or break an outfit. These don't seem to integrate well.",
        "Layering a jacket might hide the structural issues of this look.",
        "Sometimes less is more. Removing one accessory could improve the harmony.",
        "Overall, it needs a rethink. Start locally with one item you love and build around it."
    ],
    # Score 2-4 (Low - Needs Work)
    3: [
        "You're on the right track, but the execution needs polish.",
        "A better fit would elevate this outfit significantly.",
        "The color coordination is almost there, but one element feels out of place.",
        "Swap the shoes for something cleaner to upgrade the whole look.",
        "Tucking in your shirt could define your waist better and improve the silhouette.",
        "The patterns are fighting each other. Try a solid color to balance it out.",
        "It looks a bit 'heavy'. Showing a bit of ankle or wrist could add lightness.",
        "A belt is needed to break up the lines and add structure.",
        "The jacket sleeves look too long/short. Tailoring is your best friend.",
        "This outfit feels a bit repetitive. Texture variation would add interest.",
        "Great individual pieces, but they don't quite tell a cohesive story together.",
        "The neckline of the top doesn't suit the overall vibe. Try a different cut.",
        "It feels a bit generic. Add a signature accessory to make it yours.",
        "The pants verify feels awkward. Cuffing them might look more intentional.",
        "Contrast is low. Try mixing light and dark shades for more depth.",
        "The outfit seems too seasonal for the current weather/context.",
        "It's a safe choice, but a bit uninspired. Take a small fashion risk!",
        "The fabrics look a bit worn. Crisp, fresh materials look better.",
        "You're hiding your figure! Show off your shape with better draping.",
        "The accessories are a bit too loud. Let the clothes speak for themselves.",
        "A steam iron would work wonders here. Wrinkles distract from the style.",
        "The balance between casual and formal is undefined. Pick a lane.",
        "The footwear is too chunky for these pants. Try a slimmer profile.",
        "Consider your skin tone when choosing these specific colors.",
        "The collar implies formality, but the rest says gym. harmonise the message.",
        "It looks a bit crowded. giving the outfit some 'breathing room' would help.",
        "The layers are adding unnecessary bulk. streamline the silhouette.",
        "A different hairstyle might actually complement this neckline better.",
        "The logos are distracting. Minimal branding usually looks more premium.",
        "It's okay, but feels like a uniform. Personalize it!"
    ],
    # Score 4-6 (Average)
    5: [
        "This is a solid, everyday look. It works well for casual settings.",
        "Good effort! A nice watch or bracelet would act as a great cherry on top.",
        "You look comfortable, which is half the battle. Maybe dress it up slightly?",
        "The colors match well. To level up, play with textures like leather or knit.",
        "A decent outfit. Replacing the bag with a leather one would add class.",
        "Nice, but safe. A bold scarf or tie could add some needed personality.",
        "The top and bottom work together. Shoes are the only weak link here.",
        "This is functional fashion. To make it stylish, focus on the details.",
        "Not bad! A slightly better fit on the pants would make it an 8.",
        "It works. Maybe try rolling the sleeves for a more relaxed, lived-in vibe.",
        "Good color blocking. The material choice could be a bit more premium.",
        "You look presentable. A statement piece would take this from good to great.",
        "The silhouette is fine. Adding layers would create more visual interest.",
        "It's a classic combo. Make sure your grooming matches the sharpness.",
        "A fine look for running errands. For an event, elevate the footwear.",
        "The basics are there. Now it's time to accessorize thoughtfully.",
        "You blend in well. If you want to stand out, try a brighter hue.",
        "Comfortable and clean. A structured jacket could add some edge.",
        "This is a reliable go-to outfit. Keep it fresh with new accessories.",
        "The proportions are standard. Playing with lengths could make it modern.",
        "It's a balanced look. Maybe swap the denim for chinos for a change?",
        "Good utility. Ensure your pockets aren't bulging to keep lines clean.",
        "The graphics are fun. Ensure they align with the occasion's vibe.",
        "It's a cohesive color story. Texture contrast is the next step.",
        "Functional and tidy. A hat could add a fun twist if you're bold.",
        "The fit is decent. A wash or two might help the fabric settle better.",
        "It's a middle-of-the-road look. Nothing wrong, but nothing exciting.",
        "Good start. Think about how the outfit moves with you.",
        "The basics are covered. Now focus on the quality of the individual items.",
        "A respectable effort. Confidence will sell this look more than the clothes."
    ],
    # Score 6-8 (Good)
    7: [
        "Really nice look! The colors complement each other beautifully.",
        "Great style! The fit is spot on and very flattering.",
        "You look sharp. That jacket is a fantastic piece.",
        "Well put together! The shoes tie everything together perfectly.",
        "I love the texture mix here. It adds a lot of depth.",
        "This is a strong look. You clearly understand your personal style.",
        "Very chic. Simple, yet effective and elegant.",
        "Great silhouette. It highlights your best features.",
        "The accessories are perfect—not too much, not too little.",
        "You've nailed the 'smart casual' vibe here.",
        "Impressive attention to detail. The matching leathers are a nice touch.",
        "This looks effortless, which is the hardest thing to achieve. Well done.",
        "Bold choice on the pattern, and it pays off! distinctive.",
        "The layering is expert level. warm but not bulky.",
        "You look ready for anything. Versatile and stylish.",
        "Great color palette. It really suits your complexion.",
        "The drape of that fabric is lovely. excellent choice.",
        "You're owning this look. The confidence shines through.",
        "A very modern interpretation of a classic style. Fresh!",
        "Clean, crisp, and confident. A winning combination.",
        "The proportions are interesting and fashion-forward.",
        "Great use of a statement piece without letting it take over.",
        "This would photograph really well. Very photogenic outfit.",
        "You have a good eye for quality. These pieces look premium.",
        "The balance of masculine and feminine elements is intriguing.",
        "It flows well. There's a nice rhythm to the outfit.",
        "Very trendy but grounded in good taste.",
        "The transition from top to bottom is seamless.",
        "You look polished and professional but approachable.",
        "A strong 7/8. Just one small unique touch away from a 9."
    ],
    # Score 8-10 (Excellent)
    9: [
        "Absolutely stunning! This is magazine-cover worthy.",
        "Flawless execution. Every detail is considered and perfect.",
        "You look incredible! A masterclass in style and fit.",
        "Perfection. The colors, the fit, the attitude—it has it all.",
        "Wow! This is a show-stopping look. Heads will turn.",
        "Impeccable style. You could teach a class on this.",
        "The definition of sartorial elegance. Bravo!",
        "It's rare to see such a cohesive and compelling outfit. Amazing.",
        "You look radiant. The outfit enhances you perfectly.",
        "10/10! No notes, just admiration.",
        "This is high fashion. sophisticated, daring, and successful.",
        "The harmony in this outfit is artistic. Beautifully done.",
        "You look exceptionally dashing/beautiful. A triumph!",
        "This outfit tells a story. It's evocative and powerful.",
        "The tailoring is exquisite. It looks made for you.",
        "Incredible use of color. It helps you stand out in the best way.",
        "This is a power outfit. You look unstoppable.",
        "Simple, yet incredibly sophisticated. The mark of true style.",
        "Breathtakingly good. You clearly have a gift for fashion.",
        "Every element works in sympathy with the others. Symphonic.",
        "This sets the standard for how this style should be done.",
        "You look like a fashion icon. Inspiring!",
        "The vibe is immaculate. You've captured the mood perfectly.",
        "Exceptional. It's fresh, it's you, and it's perfect.",
        "A vision of style. thank you for sharing this look.",
        "Top tier. You're ready for the red carpet.",
        "Simply superb. I wouldn't change a single thread.",
        "This is the pinnacle of the aesthetic you're going for.",
        "Magnificent. You've elevated the entire room.",
        "Pure excellence. Enjoy the compliments coming your way!"
    ]
}

FALLBACK_SUMMARIES = {
    1: ["A confused mix.", "Needs rethinking.", "Disjointed effort.", "Missed the mark.", "Too chaotic."],
    3: ["Needs polish.", "Almost there.", "A bit plain.", "Lacks structure.", "Average attempt."],
    5: ["Solid casual.", "Decent daily wear.", "Safe choice.", "Functional look.", "Middle ground."],
    7: ["Sharp and stylish.", "Well put together.", "Effortlessly cool.", "Great vibes.", "Modern classic."],
    9: ["Absolute perfection.", "Runway ready.", "Stunning ensemble.", "Fashion mastery.", "Impeccable style."]
}
